In [2]:
n = 0
numero_primos = 0

while n <= 1234567:
    if n < 2:
        sol = 0
    else:
        sol = 1
        for i in range(2, int(n**0.5) + 1):
            if n % i == 0:
                sol = 0
                break
    numero_primos += sol
    n += 1

print(numero_primos)

95360


In [3]:
import numpy as np

print(f"Numpy version: {np.__version__}")

Numpy version: 1.26.3


In [ ]:
m_al = np.random.rand(1000, 10000)
print(m_al)

[[0.8831308  0.64808447 0.43126963 ... 0.72078064 0.7978612  0.48125977]
 [0.30541268 0.80920743 0.75603592 ... 0.14973835 0.66570702 0.6847077 ]
 [0.74478578 0.14312109 0.86616275 ... 0.59507946 0.2718102  0.79592092]
 ...
 [0.00360102 0.44271841 0.37610723 ... 0.01055201 0.16921901 0.64954439]
 [0.38550566 0.01172435 0.6018648  ... 0.51789674 0.62100561 0.76128904]
 [0.59409925 0.80991901 0.12607552 ... 0.16808522 0.66989115 0.85785112]]


Elemento a elemento

In [ ]:
def elemento_por_dos(m):
    m1=m
    tamaño_matriz = m1.shape
    for i in range (0,tamaño_matriz[0]):
        for j in range (0,tamaño_matriz[1]):
            m1[i,j]*=2
    return(m1)

m1=elemento_por_dos(m_al)
print(m1)
print(m_al)
#2.2 segundos

[[1.76626159 1.29616894 0.86253926 ... 1.44156127 1.59572241 0.96251954]
 [0.61082535 1.61841486 1.51207184 ... 0.2994767  1.33141404 1.36941541]
 [1.48957157 0.28624218 1.7323255  ... 1.19015892 0.54362041 1.59184184]
 ...
 [0.00720204 0.88543681 0.75221446 ... 0.02110402 0.33843802 1.29908878]
 [0.77101131 0.0234487  1.20372959 ... 1.03579348 1.24201121 1.52257808]
 [1.18819849 1.61983803 0.25215103 ... 0.33617044 1.33978229 1.71570224]]
[[1.76626159 1.29616894 0.86253926 ... 1.44156127 1.59572241 0.96251954]
 [0.61082535 1.61841486 1.51207184 ... 0.2994767  1.33141404 1.36941541]
 [1.48957157 0.28624218 1.7323255  ... 1.19015892 0.54362041 1.59184184]
 ...
 [0.00720204 0.88543681 0.75221446 ... 0.02110402 0.33843802 1.29908878]
 [0.77101131 0.0234487  1.20372959 ... 1.03579348 1.24201121 1.52257808]
 [1.18819849 1.61983803 0.25215103 ... 0.33617044 1.33978229 1.71570224]]


In [ ]:
def todo_dos(m):
    m1 = m * 2
    print(m1)

todo_dos(m_al)

#0.0

[[2.77738276 2.54662542 1.28833149 ... 0.06341285 2.3832021  1.80068656]
 [0.2367891  0.0943759  3.24015044 ... 1.53539183 2.21698062 0.94438557]
 [1.79018042 0.77418275 0.47193542 ... 0.02020677 0.43215015 1.50320654]
 ...
 [3.17345545 2.80905607 1.9357487  ... 2.00489742 3.12602752 1.61394113]
 [3.28626423 1.60531172 0.73431515 ... 1.87761389 2.45619126 3.0211478 ]
 [1.35516891 3.7640623  3.8108619  ... 3.0094888  1.8595775  3.32788402]]


In [4]:
import time
import numpy as np
import torch

#Vemos el si está la GPU disponible
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

#Las matrices aleatorias que vamos a multiplicar
M1 = np.random.rand(1000, 1000)
M2 = np.random.rand(1000, 1000)

#Pasamos las matrices a gpu
TM1 = torch.from_numpy(M1)
TM2 = torch.from_numpy(M2)

t_numpy = 0
t_gpu = 0

for _ in range(100):
    inicio = time.time()
    resultado_numpy = M1 * M2
    fin = time.time()
    t_numpy += fin - inicio



for _ in range(100):
    inicio = time.time()
    resultado_gpu = TM1*TM2
    torch.cuda.synchronize()
    fin = time.time()
    t_gpu += fin - inicio

t_promedio_numpy = t_numpy / 100
t_promedio_pytorch_gpu = t_gpu / 100

print(f"\nTiempo promedio para NumPy: {t_promedio_numpy} segundos")
print(f"Tiempo promedio para PyTorch en GPU: {t_promedio_pytorch_gpu} segundos")

Device: cuda

Tiempo promedio para NumPy: 0.0012196040153503419 segundos
Tiempo promedio para PyTorch en GPU: 0.0012101292610168456 segundos
